import { Check, ChevronsUpDown, Loader2 } from 'lucide-react';
import * as React from 'react';
import { Button } from '@/components/ui/button';
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from '@/components/ui/command';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Label } from '@/components/ui/label';
import { Skeleton } from '@/components/ui/skeleton';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import { buttonVariants } from '@/components/ui/button';
import { readApiError } from '@/lib/api-error';
import { cn } from '@/lib/utils';

/**
 * Barrel for the shadcn/ui primitives, plus the handful of app-level composites
 * built on top of them. Anything generated by the shadcn CLI lands in its own
 * file beside these and is re-exported here.
 */
export * from '@/components/ui/alert';
export * from '@/components/ui/alert-dialog';
export * from '@/components/ui/avatar';
export * from '@/components/ui/badge';
export * from '@/components/ui/button';
export * from '@/components/ui/card';
export * from '@/components/ui/checkbox';
export * from '@/components/ui/command';
export * from '@/components/ui/dialog';
export * from '@/components/ui/dropdown-menu';
export * from '@/components/ui/input';
export * from '@/components/ui/label';
export * from '@/components/ui/popover';
export * from '@/components/ui/scroll-area';
export * from '@/components/ui/select';
export * from '@/components/ui/separator';
export * from '@/components/ui/sheet';
export * from '@/components/ui/skeleton';
export * from '@/components/ui/table';
export * from '@/components/ui/tabs';
export * from '@/components/ui/textarea';
export * from '@/components/ui/tooltip';
export * from '@/components/ui/sonner';

/* ------------------------------------------------------------------ *
 * App-level composites
 * ------------------------------------------------------------------ */

export const Field = ({
  label,
  htmlFor,
  hint,
  error,
  required,
  className,
  children,
}: {
  label: string;
  htmlFor: string;
  hint?: string;
  error?: string;
  required?: boolean;
  className?: string;
  children: React.ReactNode;
}) => (
  // min-w-0 so a field inside a grid track can shrink instead of forcing the row wider.
  <div className={cn('mb-4 min-w-0', className)}>
    <Label htmlFor={htmlFor} required={required}>
      {label}
    </Label>
    {children}
    {hint && !error ? (
      <p id={`${htmlFor}-hint`} className="mt-1 text-xs text-muted-foreground">
        {hint}
      </p>
    ) : null}
    {error ? (
      <p id={`${htmlFor}-error`} role="alert" className="mt-1 text-xs font-medium text-destructive">
        {error}
      </p>
    ) : null}
  </div>
);

/**
 * Radix reserves the empty string: an item may not use it, and a root value of
 * '' is what makes the placeholder show. Those two rules collide for the "All …"
 * filters here, whose real value is ''.
 *
 * So the swap to a sentinel happens only when an option actually claims '' — a
 * filter's "All statuses" row. Where no option does, '' keeps its Radix meaning
 * of "nothing picked yet" and the placeholder renders. Callers always see ''.
 */
const ANY = '__any__';

export interface SelectOption {
  value: string;
  label: string;
  disabled?: boolean;
}

export const SimpleSelect = ({
  id,
  value,
  onValueChange,
  options,
  placeholder,
  disabled,
  className,
  ...props
}: {
  id?: string;
  value: string;
  onValueChange: (value: string) => void;
  options: SelectOption[];
  placeholder?: string;
  disabled?: boolean;
  className?: string;
} & Pick<React.AriaAttributes, 'aria-label' | 'aria-describedby'>) => {
  const hasEmptyOption = options.some((option) => option.value === '');
  const encode = (raw: string) => (raw === '' && hasEmptyOption ? ANY : raw);

  return (
    <Select
      value={encode(value)}
      onValueChange={(next) => onValueChange(next === ANY ? '' : next)}
      disabled={disabled}
    >
      <SelectTrigger id={id} className={className} {...props}>
        <SelectValue placeholder={placeholder} />
      </SelectTrigger>
      <SelectContent>
        {options.map((option) => (
          <SelectItem key={option.value} value={encode(option.value)} disabled={option.disabled}>
            {option.label}
          </SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
};

/**
 * Type-to-filter picker for lists a plain select handles badly — the contact
 * picker can hold hundreds of names, where a dropdown means scrolling blind.
 */
export const Combobox = ({
  id,
  value,
  onValueChange,
  options,
  placeholder = 'Select an option',
  searchPlaceholder = 'Search…',
  emptyMessage = 'Nothing found.',
  disabled,
  className,
}: {
  id?: string;
  value: string;
  onValueChange: (value: string) => void;
  options: SelectOption[];
  placeholder?: string;
  searchPlaceholder?: string;
  emptyMessage?: string;
  disabled?: boolean;
  className?: string;
}) => {
  const [open, setOpen] = React.useState(false);
  const selected = options.find((option) => option.value === value);

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <Button
          id={id}
          type="button"
          variant="outline"
          role="combobox"
          aria-expanded={open}
          disabled={disabled}
          className={cn(
            'w-full justify-between px-3 font-normal',
            !selected && 'text-muted-foreground',
            className,
          )}
        >
          <span className="truncate">{selected ? selected.label : placeholder}</span>
          <ChevronsUpDown className="shrink-0 opacity-50" aria-hidden="true" />
        </Button>
      </PopoverTrigger>
      <PopoverContent className="w-[--radix-popover-trigger-width] p-0">
        <Command>
          <CommandInput placeholder={searchPlaceholder} />
          <CommandList>
            <CommandEmpty>{emptyMessage}</CommandEmpty>
            <CommandGroup>
              {options.map((option) => (
                <CommandItem
                  key={option.value}
                  // cmdk filters on this, not on the value we store.
                  value={option.label}
                  disabled={option.disabled}
                  onSelect={() => {
                    onValueChange(option.value === value ? '' : option.value);
                    setOpen(false);
                  }}
                >
                  <Check
                    className={cn('size-4', option.value === value ? 'opacity-100' : 'opacity-0')}
                    aria-hidden="true"
                  />
                  <span className="truncate">{option.label}</span>
                </CommandItem>
              ))}
            </CommandGroup>
          </CommandList>
        </Command>
      </PopoverContent>
    </Popover>
  );
};

export const Spinner = ({ label = 'Loading' }: { label?: string }) => (
  <div role="status" className="flex items-center gap-2 py-8 text-sm text-muted-foreground">
    <Loader2 className="size-4 animate-spin" aria-hidden="true" />
    <span>{label}&hellip;</span>
  </div>
);

/** Loading state that keeps the page's shape instead of collapsing it to a spinner. */
export const TableSkeleton = ({ rows = 5, columns = 5 }: { rows?: number; columns?: number }) => (
  <div role="status" aria-label="Loading" className="space-y-2">
    {Array.from({ length: rows }).map((_row, rowIndex) => (
      <div
        key={rowIndex}
        className="flex flex-col gap-2 rounded-lg border border-border p-3 md:flex-row md:items-center md:gap-4 md:border-0 md:p-0"
      >
        {Array.from({ length: columns }).map((_column, columnIndex) => (
          <Skeleton key={columnIndex} className="h-5 flex-1" />
        ))}
      </div>
    ))}
  </div>
);

export const EmptyState = ({
  title,
  description,
  action,
}: {
  title: string;
  description: string;
  action?: React.ReactNode;
}) => (
  <div className="rounded-xl border border-dashed border-border px-4 py-10 text-center sm:px-6 sm:py-12">
    <p className="text-sm font-semibold">{title}</p>
    <p className="mx-auto mt-1 max-w-md text-sm text-muted-foreground">{description}</p>
    {action ? <div className="mt-4 flex justify-center">{action}</div> : null}
  </div>
);

/**
 * Renders an API failure the way the API described it: the headline sentence, and
 * below it every field the server rejected with the reason for each. Without the
 * list a validation failure reads as "Request validation failed" and the user has
 * no idea which input to fix.
 */
export const ApiErrorMessage = ({
  error,
  fallback,
  className,
}: {
  error: unknown;
  fallback: string;
  className?: string;
}) => {
  const { message, issues } = readApiError(error, fallback);
  return (
    <div className={className}>
      <p>{message}</p>
      {issues.length > 0 ? (
        <ul className="mt-2 space-y-1">
          {issues.map((issue, index) => (
            <li key={`${issue.path}-${index}`} className="flex gap-1.5">
              <span aria-hidden="true">•</span>
              <span>
                {issue.label ? <span className="font-medium">{issue.label}: </span> : null}
                {issue.message}
              </span>
            </li>
          ))}
        </ul>
      ) : null}
    </div>
  );
};

export const ErrorState = ({
  error,
  onRetry,
  fallback = 'Please try again.',
}: {
  error: unknown;
  onRetry?: () => void;
  fallback?: string;
}) => (
  <div role="alert" className="rounded-lg border border-destructive/40 bg-destructive/5 p-4">
    <p className="text-sm font-semibold text-destructive">Something went wrong</p>
    <ApiErrorMessage
      error={error}
      fallback={fallback}
      className="mt-1 text-sm text-muted-foreground"
    />
    {onRetry ? (
      <Button variant="outline" size="sm" className="mt-3" onClick={onRetry}>
        Try again
      </Button>
    ) : null}
  </div>
);

/** Live region so async results are announced, not just shown. */
export const StatusMessage = ({
  tone,
  children,
}: {
  tone: 'success' | 'error';
  children: React.ReactNode;
}) => (
  <div
    role="status"
    aria-live="polite"
    className={cn(
      'mt-3 rounded-md px-3 py-2 text-sm',
      tone === 'success' ? 'bg-success/10 text-success' : 'bg-destructive/10 text-destructive',
    )}
  >
    {children}
  </div>
);

/**
 * A destructive action gets a real modal rather than a second button appearing
 * in a table row — on a phone the inline pattern pushed the row's other controls
 * off screen, and it was easy to confirm the wrong row.
 */
export const ConfirmDialog = ({
  open,
  onOpenChange,
  title,
  description,
  confirmLabel = 'Confirm',
  cancelLabel = 'Cancel',
  loading,
  onConfirm,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  title: string;
  description: string;
  confirmLabel?: string;
  cancelLabel?: string;
  loading?: boolean;
  onConfirm: () => void;
}) => (
  <AlertDialog open={open} onOpenChange={onOpenChange}>
    <AlertDialogContent>
      <AlertDialogHeader>
        <AlertDialogTitle>{title}</AlertDialogTitle>
        <AlertDialogDescription>{description}</AlertDialogDescription>
      </AlertDialogHeader>
      <AlertDialogFooter>
        <AlertDialogCancel disabled={loading}>{cancelLabel}</AlertDialogCancel>
        <AlertDialogAction
          className={cn(buttonVariants({ variant: 'destructive' }))}
          disabled={loading}
          aria-busy={loading || undefined}
          // Radix closes on click; the mutation's own state drives the row afterwards.
          onClick={onConfirm}
        >
          {loading ? <Loader2 className="size-4 animate-spin" aria-hidden="true" /> : null}
          {confirmLabel}
        </AlertDialogAction>
      </AlertDialogFooter>
    </AlertDialogContent>
  </AlertDialog>
);
